/* SATU SUMBER DATA SALES — ubah file ini, semua halaman ikut berubah.
 * Semua entri di bawah adalah CONTOH pemetaan sales, bukan klaim cabang resmi.
 * wa: format internasional tanpa +/spasi (62...), verified: true HANYA setelah dikonfirmasi.
 * x/y: posisi pada peta ilustratif, bukan koordinat GPS. Jangan digunakan untuk rute kantor.
 * Nomor dengan huruf x otomatis diblokir. Tidak ada pengiriman otomatis.
 */
window.ASJ_LOCATIONS = {
  branches: [
    {
      id: "pontianak",
      label: "Pontianak",
      sales: "Sales Pontianak",
      wa: "6285792951129",
      verified: true,
      address: "Alamat cabang belum diisi.",
      x: 32,
      y: 50,
    },
    {
      id: "singkawang",
      label: "Singkawang",
      sales: "Sales Singkawang",
      wa: "6285754365803",
      verified: true,
      address: "Alamat cabang belum diisi.",
      x: 25,
      y: 31,
    },
    {
      id: "kuburaya",
      label: "Kubu Raya",
      sales: "Sales Kubu Raya",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 39,
      y: 60,
    },
    {
      id: "mempawah",
      label: "Mempawah",
      sales: "Sales Mempawah",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 28,
      y: 41,
    },
    {
      id: "sambas",
      label: "Sambas",
      sales: "Sales Sambas",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 32,
      y: 20,
    },
    {
      id: "bengkayang",
      label: "Bengkayang",
      sales: "Sales Bengkayang",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 41,
      y: 33,
    },
    {
      id: "landak",
      label: "Landak",
      sales: "Sales Landak",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 51,
      y: 43,
    },
    {
      id: "sanggau",
      label: "Sanggau",
      sales: "Sales Sanggau",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 65,
      y: 47,
    },
    {
      id: "sekadau",
      label: "Sekadau",
      sales: "Sales Sekadau",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 73,
      y: 38,
    },
    {
      id: "sintang",
      label: "Sintang",
      sales: "Sales Sintang",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 82,
      y: 29,
    },
    {
      id: "kayongutara",
      label: "Kayong Utara",
      sales: "Sales Kayong Utara",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 43,
      y: 75,
    },
    {
      id: "ketapang",
      label: "Ketapang",
      sales: "Sales Ketapang",
      wa: "62xxxxxxxxxxx",
      verified: false,
      address: "Alamat cabang belum diisi.",
      x: 57,
      y: 88,
    },
  ],
};
window.ASJ_LOCATIONS.regions = window.ASJ_LOCATIONS.branches;
window.ASJ_LOCATIONS.adminWhatsApp = "62xxxxxxxxxxx";

window.ASJ_LOCATIONS.branches.push({
  id: "lainnya",
  label: "Daerah lain / belum tahu",
  sales: "Admin penentuan wilayah",
  wa: "62xxxxxxxxxxx",
  verified: false,
  address: "Sebutkan alamat tujuan lengkap.",
});
